### ISSUE TITLE
Shiny application

### ISSUE THREAD

**Issue by Samuel-ZDM** [mralbu/coronavirusbrazil#1]
The graphics system is very cool. I found it very interesting.
I also created an application using shiny, but much simpler.
https://covid19brazil.shinyapps.io/coronaBrazil/

**Comment by mralbu** [comment]
Cool! Not sure if you're aware, but Rstudio has announced free hosting for covid apps on shinyapps.io.
https://blog.rstudio.com/2020/04/17/rstudio-and-covid-19/
Cheers

**Comment by Samuel-ZDM** [comment]
Very nice! I didn't know this. Very good. Thanks.
